branches:
  only:
    - test

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install coveralls pytest-cov codecov
  - python setup.py install

script:
  - py.test --cov

after_success:
  - coveralls
  - codecov
